FSK-20 Make general fixes
taptima/skeleton-front-end pull request #14
Opened 2022-04-14 08:29 UTC by ChernavtsevTaptima

2022-05-02 05:38 UTC, ChernavtsevTaptima commented on src/presentation/hook/windowSize/useBreakpoint.ts
> +const lastBreakpointKey = breakpointKeys.at(-1) as BreakpointKeyT;
Будет брать последний брейкпоинт из енама. Например, "Xl"

2022-05-12 05:29 UTC, zabluda17 commented on src/presentation/hook/windowSize/useBreakpointIsLower.ts
> +export default function useBreakpointIsLower(breakpointKey: keyof typeof Breakpoint): boolean {
Можно, по аналогии, greater добавить

2022-05-19 00:00 UTC, ChernavtsevTaptima commented on src/presentation/hook/windowSize/useBreakpointIsLower.ts
> +export default function useBreakpointIsLower(breakpointKey: keyof typeof Breakpoint): boolean {
++

2022-05-19 09:19 UTC, DmitriyZvezdetckiy commented on src/presentation/hook/windowSize/useBreakpoint.ts
> +const lastBreakpointKey = breakpointKeys.at(-1) as BreakpointKeyT;
Надо бабел

2022-05-19 09:28 UTC, DmitriyZvezdetckiy requested changes

2022-05-19 09:28 UTC, DmitriyZvezdetckiy commented on src/presentation/component/common/typography/Link/index.tsx
> +    prefetch?: boolean;
Давай пикнем пропсы из NextLink, возможно несколько

2022-05-19 09:28 UTC, DmitriyZvezdetckiy commented on src/presentation/component/common/typography/Link/styles.ts
> +export const ALink = styled(Text)`
Почему А?

2022-05-19 09:28 UTC, DmitriyZvezdetckiy commented on src/presentation/hook/clickAwayListener.ts
> +const useClickAwayListener = (
Я не понимаю зачем это в скелетоне, появилось только на табаках, на других проектах не использовалось

2022-05-19 09:28 UTC, DmitriyZvezdetckiy commented on src/shared-kernel.d.ts
> +declare namespace Time {
Давай всё таки global файл назовём

2022-05-22 04:19 UTC, ChernavtsevTaptima commented on src/presentation/component/common/typography/Link/styles.ts
> +export const ALink = styled(Text)`
++

2022-05-22 04:25 UTC, ChernavtsevTaptima commented on src/presentation/component/common/typography/Link/index.tsx
> +    prefetch?: boolean;
++

2022-05-22 04:30 UTC, ChernavtsevTaptima commented on src/presentation/hook/clickAwayListener.ts
> +const useClickAwayListener = (
++

2022-05-22 04:31 UTC, ChernavtsevTaptima commented on src/shared-kernel.d.ts
> +declare namespace Time {
++

2022-05-22 23:39 UTC, ChernavtsevTaptima commented on src/presentation/hook/windowSize/useBreakpoint.ts
> +const lastBreakpointKey = breakpointKeys.at(-1) as BreakpointKeyT;
Будет исправлено в отдельной ветке и задаче FSK-48

2022-06-05 07:12 UTC, DmitriyZvezdetckiy approved these changes

2022-06-05 07:12 UTC, merged