Implement 'createSSGPage' & 'createSSRPage'
taptima/skeleton-front-end pull request #16
Opened 2022-05-02 09:12 UTC by ChernavtsevTaptima

2022-05-11 04:18 UTC, ChernavtsevTaptima commented on src/presentation/component/layout/index.tsx
> - * Warning!
Коммент больше не актуален, можно хоть 10 'return' написать

2022-05-12 06:20 UTC, zabluda17 commented on src/presentation/component/layout/styles.ts
> +    ${({ css: mainCss }) => mainCss}
Пустая строка выше

2022-05-12 06:20 UTC, zabluda17 commented on src/presentation/component/page/error/index.tsx
> +    if (statusCode === HttpStatusCode.InternalServerError) {
А если мапку создать по кодам ошибки?

2022-05-12 06:20 UTC, zabluda17 commented on src/presentation/component/page/error/index.tsx
> +            <br />
Можно стилизовать и сделать красивую base error ошибку

2022-05-12 06:20 UTC, zabluda17 commented on src/presentation/component/layout/styles.ts
> +    padding-left: ${({ isWithContainer }) => (isWithContainer ? 'var(--main-gutter)' : 0)};
Это в каком случае понадобятся здесь паддинги? Это ведь глобальный main

2022-05-16 01:56 UTC, DmitriyZvezdetckiy commented on src/presentation/component/layout/styles.ts
> +    padding-left: ${({ isWithContainer }) => (isWithContainer ? 'var(--main-gutter)' : 0)};
А если выносить Container в main, то нужно ещё max-width указывать, слишком много всего ложится в этот компонент, при том что сам Container не всегда нужен, где-то лучше локально оборачивать. Не думаю что здесь это нужно

2022-05-16 01:57 UTC, DmitriyZvezdetckiy commented on src/presentation/component/page/error/index.tsx
> +            <br />
Согласен, кастомная страница ошибки по умолчанию, была бы кстати

2022-05-16 02:10 UTC, DmitriyZvezdetckiy requested changes

2022-05-16 02:10 UTC, DmitriyZvezdetckiy commented on src/presentation/controller/UiGlobalController.ts
> +    private readonly _privacyLock = new ReactiveState<LayoutConfig['isLocked']>(false);
Я за то чтобы поля объявлялись до их использования, то есть в самом начале класса

2022-05-16 02:10 UTC, DmitriyZvezdetckiy commented on src/presentation/pageBuilder/createPage.tsx
> +                setIsPagePrivacyLocked(true);
Может не будем в `handleLayoutUpdateOnRouteChange`, сетить что страница разрешена, а потом здесь её блокировать, а сразу здесь: `setIsPagePrivacyLocked(isPageAllowedForUser)`, чтобы в одном месте это контролировалось

2022-05-18 04:08 UTC, U256 commented on src/presentation/component/layout/styles.ts
> +    ${({ css: mainCss }) => mainCss}
++

2022-05-18 04:15 UTC, U256 commented on src/presentation/component/page/error/index.tsx
> +    if (statusCode === HttpStatusCode.InternalServerError) {
++

2022-05-18 04:22 UTC, U256 commented on src/presentation/component/page/error/index.tsx
> +            <br />
++

2022-05-18 04:25 UTC, ChernavtsevTaptima commented on src/presentation/component/layout/styles.ts
> +    padding-left: ${({ isWithContainer }) => (isWithContainer ? 'var(--main-gutter)' : 0)};
Я это сделал, чтобы избавиться от уровня 1 бесполезной вложенности

2022-05-18 04:25 UTC, ChernavtsevTaptima commented on src/presentation/controller/UiGlobalController.ts
> +    private readonly _privacyLock = new ReactiveState<LayoutConfig['isLocked']>(false);
++

2022-05-18 04:30 UTC, ChernavtsevTaptima commented on src/presentation/pageBuilder/createPage.tsx
> +                setIsPagePrivacyLocked(true);
++

2022-05-18 04:57 UTC, DmitriyZvezdetckiy approved these changes

2022-05-18 05:01 UTC, merged