feat: implement SSG & SSR page creation helpers
taptima/skeleton-front-end pull request #22
Opened 2022-06-05 07:21 UTC by ChernavtsevTaptima

2022-06-05 09:31 UTC, ChernavtsevTaptima commented on src/presentation/pageBuilder/createPage.tsx
> +        return isPageAllowedForUser ? <PageComponent /> : <PrivatePage />;
Только так можно добиться полной замены компонента. Идея с состоянием "заблокированности" в контроллере оказалась дырявой, т.к. в компоненте отрабатывал эффект и только потом компонент подменялся сообщением "Доступ закрыт"

2022-07-11 01:49 UTC, DmitriyZvezdetckiy requested changes

2022-07-11 01:49 UTC, DmitriyZvezdetckiy commented on src/pages/_app.tsx
> +            appInitialAction().then();
Сюда тоже нужен `catch`

2022-07-11 01:49 UTC, DmitriyZvezdetckiy commented on src/presentation/pageBuilder/createPage.tsx
> +        if (!isAppDataHydrated && appData && !isServer()) {
`appData` на клиенте будет пустым объектом `getInitialPage` так возвращает ниже

2022-07-11 01:49 UTC, DmitriyZvezdetckiy commented on src/presentation/pageBuilder/createSSGPage.tsx
> +    const Page: NextPage = (props) => {
`NextPage<StaticPageInitialPropsT>` и `as` не нужен

2022-07-11 01:49 UTC, DmitriyZvezdetckiy commented on src/presentation/pageBuilder/createSSGPage.tsx
> +    onRequest: (container: ContainerT, nextPageContext: GetStaticPropsContext<Q>) => Promise<void>,
Надо бы это заменить на объект, или дёрнуть типы из некста

2022-07-11 02:08 UTC, zabluda17 commented on src/pages/_app.tsx
> +            appInitialAction().then();
у сука

2022-07-11 03:44 UTC, zabluda17 commented on src/presentation/component/page/error/index.tsx
> +import React, { FC } from 'react';
?

2022-07-11 09:14 UTC, ChernavtsevTaptima commented on src/presentation/component/page/error/index.tsx
> +            <Link href={HOME}>На главную</Link>
Дима, почему ты сказал поменять некст ссылку на обычную?

2022-07-11 09:14 UTC, ChernavtsevTaptima commented on src/presentation/component/page/error/index.tsx
> +            <Link href={HOME}>На главную</Link>
@DmitriyZvezdetckiy

2022-07-11 09:16 UTC, ChernavtsevTaptima commented on src/pages/_app.tsx
> +            appInitialAction().then();
++

2022-07-11 09:17 UTC, ChernavtsevTaptima commented on src/presentation/pageBuilder/createSSGPage.tsx
> +    const Page: NextPage = (props) => {
Так не сработает

2022-07-11 09:18 UTC, ChernavtsevTaptima commented on src/presentation/component/page/error/index.tsx
> +import React, { FC } from 'react';
++

2022-07-11 09:20 UTC, ChernavtsevTaptima commented on src/presentation/pageBuilder/createSSGPage.tsx
> +    onRequest: (container: ContainerT, nextPageContext: GetStaticPropsContext<Q>) => Promise<void>,
Из некста сложно, там перегруженный тип. Заменил на объект

2022-07-11 09:27 UTC, ChernavtsevTaptima commented on src/presentation/pageBuilder/createPage.tsx
> +        if (!isAppDataHydrated && appData && !isServer()) {
`import Controller from 'presentation/component/page/static/Controller';

export default createPage(HomePage, {
    getInitialProps: async (container) => {
        await container.get(Controller).initialAction()
    }
});`

Добавь на главную и залогируй что-нибудь внутри блока. Ты удивишься, но на сервере это тоже отработает.

2022-07-12 01:42 UTC, DmitriyZvezdetckiy commented on src/presentation/component/page/error/index.tsx
> +            <Link href={HOME}>На главную</Link>
Я не говорил такого) Я предлагал вообще убрать это

2022-07-12 01:42 UTC, DmitriyZvezdetckiy approved these changes

2022-07-12 04:25 UTC, zabluda17 commented on src/presentation/component/page/error/index.tsx
> +            <Link href={HOME}>На главную</Link>
next link

2022-07-12 04:35 UTC, merged